# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: ace-custom-bar-gitops-helm
  namespace: my-cp4i

spec:
  license: L-APEH-C49KZH
  use: CloudPakForIntegrationNonProduction

version: '12.0.1.0-r4'
barURL: ''

configuration:
  credentials: jfrog-credentials
  policy: policy-policyname
  
resources: {}
